name: college_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl: ^0.19.0
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  carousel_slider: ^4.2.1
  flutter_custom_clippers: ^2.1.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  firebase_database: ^10.4.0
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1
  table_calendar: ^3.0.9
  fluttertoast: ^8.2.4
  font_awesome_flutter: ^10.6.0
  shimmer: ^3.0.0
  package_info_plus: ^5.0.1
  url_launcher: ^6.2.4
  easy_splash_screen: ^1.0.4

dependency_overrides:
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:

  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/home/card_image/
    - assets/images/home/slider_image/
    - assets/images/student/card_image/
    - assets/images/teacher/card_image/
    - assets/icon/launcher_icon.png
