name: college_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  provider: ^6.0.2
  shared_preferences: ^2.0.13
  carousel_slider: ^4.0.0
  flutter_custom_clippers: ^2.0.0
  firebase_core: ^1.13.1
  firebase_auth: ^3.3.11
  firebase_database: ^9.0.8
  cloud_firestore: ^3.1.10
  firebase_storage: ^10.2.9
  image_picker: ^0.8.4+11
  cached_network_image: ^3.2.0
  table_calendar: ^3.0.5
  fluttertoast: ^8.0.9
  modal_bottom_sheet: ^2.0.1
  font_awesome_flutter: ^10.1.0
  shimmer: ^2.0.0
  internet_connection_checker: ^0.0.1+4
  package_info_plus: ^1.4.2
  url_launcher: ^6.1.5
  easy_splash_screen: ^1.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:

  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/home/card_image/
    - assets/images/home/slider_image/
    - assets/images/student/card_image/
    - assets/images/teacher/card_image/
    - assets/icon/launcher_icon.png
